CONTRIBUTING.md, dev-requirements.txt
- Development bootstrap requirements contained invalid reference.
- Added how to activate virtualenv to getting started section of docs
=> Fix dev bootstrap and extend documentation

gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/catalog/data_source/action_requests/__init__.py, gooddata-sdk/gooddata_sdk/catalog/data_source/action_requests/ldm_request.py, gooddata-sdk/gooddata_sdk/catalog/data_source/service.py, gooddata-sdk/gooddata_sdk/catalog/workspace/service.py, gooddata-sdk/tests/catalog/fixtures/data_sources/demo_generate_logical_model.json, gooddata-sdk/tests/catalog/fixtures/data_sources/demo_register_upload_notification.json, gooddata-sdk/tests/catalog/test_catalog_data_source.py, gooddata-sdk/tests/gd_test_config.yaml
get_declarative_ldm, store_declarative_ldm, load_and_put_declarative_ldm, put_declarative_ldm, get_declarative_analytics_model, put_declarative_analytics_model, store_declarative_analytics_model, load_and_put_declarative_analytics_model moved to CatalogWorkspaceContentService
Created 2 new methods in CatalogDataSourceService - generate_logical_model, register_upload_notification.
=> NAS3355 - CatalogDataSourceService extension 

gooddata-sdk/requirements.txt, gooddata-sdk/setup.py
combining SDK with other libs is not possible due to this strict version lock
=> TRIVIAL: relax version of PyYAML library

gooddata-pandas/gooddata_pandas/utils.py, gooddata-pandas/requirements.txt, gooddata-pandas/setup.py
* set minimum and maximum version for pandas library
* changed import in utils.py which caused raising FutureWarning
=> NAS-3276 fixed future warning in GoodPandas

gooddata-sdk/gooddata_sdk/catalog/organization/entity_model/organization.py, gooddata-sdk/gooddata_sdk/catalog/organization/service.py, gooddata-sdk/gooddata_sdk/catalog/user/declarative_model/user.py, gooddata-sdk/gooddata_sdk/catalog/user/declarative_model/user_group.py, gooddata-sdk/gooddata_sdk/catalog/user/entity_model/user.py, gooddata-sdk/gooddata_sdk/catalog/user/entity_model/user_group.py, gooddata-sdk/gooddata_sdk/catalog/user/service.py, gooddata-sdk/tests/catalog/fixtures/organization/update_name.json, gooddata-sdk/tests/catalog/fixtures/organization/update_oidc_settings.json, gooddata-sdk/tests/catalog/fixtures/users/create_delete_user.json, gooddata-sdk/tests/catalog/fixtures/users/create_delete_user_group.json, gooddata-sdk/tests/catalog/fixtures/users/update_user.json, gooddata-sdk/tests/catalog/fixtures/users/update_user_group.json, gooddata-sdk/tests/catalog/load/gooddata_layouts/default/user_groups/adminGroup.yaml, gooddata-sdk/tests/catalog/load/gooddata_layouts/default/user_groups/adminQA1Group.yaml, gooddata-sdk/tests/catalog/load/gooddata_layouts/default/user_groups/demoGroup.yaml, gooddata-sdk/tests/catalog/load/gooddata_layouts/default/user_groups/user_groups.yaml, gooddata-sdk/tests/catalog/load/gooddata_layouts/default/user_groups/visitorsGroup.yaml, gooddata-sdk/tests/catalog/load/gooddata_layouts/default/users/admin.yaml, gooddata-sdk/tests/catalog/load/gooddata_layouts/default/users/demo.yaml, gooddata-sdk/tests/catalog/load/gooddata_layouts/default/users/demo2.yaml, gooddata-sdk/tests/catalog/load/gooddata_layouts/default/users/users.yaml, gooddata-sdk/tests/catalog/test_catalog_organization.py, gooddata-sdk/tests/catalog/test_catalog_user_service.py
* added method update_oidc_parameters in organization service
* changed create to create_or_update for users and user groups
* changed storing users and user groups to layout
* added test support
=> NAS-3868 extend user and organisation service 

gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/catalog/base.py, gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/data_source.py, gooddata-sdk/gooddata_sdk/catalog/identifier.py, gooddata-sdk/gooddata_sdk/catalog/permissions/declarative_model/__init__.py, gooddata-sdk/gooddata_sdk/catalog/permissions/declarative_model/permission.py, gooddata-sdk/gooddata_sdk/catalog/permissions/service.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/workspace.py, gooddata-sdk/gooddata_sdk/sdk.py, gooddata-sdk/tests/catalog/expected/declarative_workspace_permissions.json, gooddata-sdk/tests/catalog/fixtures/permissions/get_declarative_permissions.json, gooddata-sdk/tests/catalog/fixtures/permissions/put_declarative_permissions.json, gooddata-sdk/tests/catalog/test_catalog_permission.py
Added:
* permission service
* validation for permission names
* test support
=> NAS-3893 add permission service

gooddata-fdw/gooddata_fdw/column_utils.py, gooddata-pandas/gooddata_pandas/dataframe.py, gooddata-pandas/gooddata_pandas/series.py, gooddata-sdk/gooddata_sdk/catalog/workspace/model_container.py, gooddata-sdk/gooddata_sdk/catalog/workspace/service.py, gooddata-sdk/gooddata_sdk/compute/model/execution.py, gooddata-sdk/gooddata_sdk/compute/service.py, gooddata-sdk/gooddata_sdk/insight.py, gooddata-sdk/gooddata_sdk/support.py, gooddata-sdk/gooddata_sdk/table.py, gooddata-sdk/gooddata_sdk/type_converter.py, gooddata-sdk/gooddata_sdk/utils.py
It seems that docstring annotations are quite fragile and have to follow very strict indentation rules to be parsed correctly by Sphinx autodoc. We should investigate if it's possible to automate this with some linters.
=> Fix docstring annotations for better rendering online

gooddata-sdk/docs/services/index.rst
Sacrificed extra description on the [Services page](https://gooddata-sdk.readthedocs.io/en/latest/services/index.html), but got TOC in the left menu working properly. IMHO it's more important for a new user to understand which part of docs you're in.
=> Updated the way TOC is defined for Python SDK Services page in docs

gooddata-sdk/gooddata_sdk/__init__.py
handy when processing declarative documents and want to type arguments of functions properly
=> TRIVIAL: extend list of classes exported from SDK init

.sonar.settings
- Retrun back custom setup for sonarqube. It is hopefully just temporary action.
- Tune setup for both sonarqube and sonarcloud - specify supported
python versions
=> TRIVIAL: dual sonar setup

gooddata-fdw/docs/installation.rst, gooddata-fdw/sql/import_gooddata.sql
* added view creation after foreign tables import
* code snippet change in documentation forcing rebuild services
=> NAS-4268 create view related to foreign table

gooddata-pandas/gooddata_pandas/result_convertor.py
* because pandas.io.formats.style.Styler.to_excel expects empty headers with None otherwise it takes the value and prints it which is not expected for empty string in this case
=> XSH-867: Use None in DataFrame index/column names for missing headers

gooddata-sdk/docs/services/catalog-data-source.rst, gooddata-sdk/docs/services/catalog-workspace-content.rst, gooddata-sdk/docs/services/compute.rst, gooddata-sdk/docs/services/table.rst
* delete irrelevant Entity methods from compute.rst and table.rst #
*  add new methods to catalog-data-source.rst and catalog-workspace-content.rst
=> Documentation update

docs/content/en/docs/workspace/workspaces/load_and_put_declarative_workspace.md
(cherry picked from commit fcbbb45fa13d3e749ac2411e165318255ce1b97f)
=> TRIVIAL: fix typo in example

.github/workflows/netlify-deploy-preview.yaml
When we build the preview in pull_request_target action we want to get only docs/content/en (the actual documentation files) from the PR.
The rest of the repository can be used from master branch (and fork). This is more secure as we don't allow users to inject malicious commands in the building process (e.g. scripts in package.json files).
=> BUGFIX: Get only docs/content/en from a PR

gooddata-fdw/Dockerfile
There were several issues with the latest postgres:12.15. First, docker-compose build gooddata-fdw stopped working out of the box with the missing pg_config. I tried to fix it by adding libpq-dev, but it failed with an incompatible version of clang. The expected version is 15, but the installed is 16. Therefore, I decided to lock the base image to postgres:12.14-alpine which works.
=> RELATED: PSDK-149 fix failed fdw docker image build with postgres:12.15

gooddata-fdw/.readthedocs.yaml, gooddata-pandas/.readthedocs.yaml
Documentation is not very clear. It turned out, paths are relative to the root of repository.
=> PSDK-152: fix paths in .readthedocs.yaml

gooddata-sdk/gooddata_sdk/catalog/data_source/service.py, gooddata-sdk/tests/catalog/fixtures/data_sources/patch.yaml
Caused by following change in upstream API: https://github.com/gooddata/gdc-nas/commit/4a81a447e7541bfbf5ae691342c228b3138e00dd
=> Add missing url param to ds patch attributes

gooddata-dbt/gooddata_dbt/dbt/tables.py
Missing condition for empty ldm_type caused attributes were generated for when ldm_type was reference and not DATE.
=> TRIVIAL: gooddata-dbt - do not generate attributes in some cases

gooddata-dbt/gooddata_dbt/dbt/cloud.py
Caused by unification of env variables in blueprint repo gooddata-data-pipeline
=> TRIVIAL: gooddata-dbt - rename user/pwd env variables

gooddata-dbt/gooddata_dbt/dbt/cloud.py
dbt cloud does not accept both, it returns error "git_branch and git_sha cannot both be specified".
=> TRIVIAL: gooddata-dbt - send only commit_sha to dbt cloud

gooddata-dbt/gooddata_dbt/dbt_plugin.py, gooddata-dbt/gooddata_dbt/utils.py
We do not want to expand GITLAB_TOKEN before merge, attackers could print it in their MRs
=> TRIVIAL: gooddata-dbt - notify to MR only if GITLAB_TOKEN is set

gooddata-dbt/setup.py
Note: This is only a temporal fix. It's necessary to adapt tbump rule for gooddata-dbt plugin.
=> TRIVIAL: bump version of dependency

gooddata-dbt/gooddata_dbt/dbt/tables.py
for column related entities (attributes, facts, ...)
=> TRIVIAL: gooddata-dbt - allow to override LDM ID

gooddata-dbt/gooddata_dbt/dbt/tables.py
=> TRIVIAL: gooddata-dbt - allow to override LDM ID part2

gooddata-dbt/gooddata_dbt/dbt_plugin.py, gooddata-dbt/gooddata_dbt/gooddata/config.py, gooddata-dbt/gooddata_example.yml
=> TRIVIAL: gooddata-dbt - allow skipping tests of specific insights

docs/content/en/docs/_index.md, docs/content/en/docs/administration/organization/_index.md, docs/content/en/docs/administration/permissions/_index.md, docs/content/en/docs/administration/user-groups/_index.md, docs/content/en/docs/administration/users-and-user-groups/_index.md, docs/content/en/docs/administration/users/_index.md, docs/content/en/docs/data/data-source/_index.md, docs/content/en/docs/data/physical-data-model/_index.md, docs/content/en/docs/getting-started.md, docs/content/en/docs/installation.md, docs/content/en/docs/workspace-content/logical-data-model/_index.md, docs/content/en/docs/workspace/workspace-data-filters/_index.md, docs/layouts/partials/navbar.html
Removing all the redirects by replacing  /developers/cloud-native/ to /docs/cloud/.
Tried to build the documentation locally and no /developers/cloud-native/ links were present.
=> WEB-4008: Clean up redirects in docs

scripts/generate.sh
Note that `find .. -type d -name 'gooddata-*'` takes too long. Instead of that, we should use `ls -d gooddata-*`, which is much faster.
=> TRIVIAL: change listing directories command

scripts/next_dev.sh
They have already been deprecated.
Once the related GitHub action is removed, we can revert this PR
=> TRIVIAL: skip alpha releases in next_dev.sh

.github/workflows/netlify-deploy.yaml
The NETLIFY_SITE_ID is no longer a secret
=> TRIVIAL: fix netlify manual deploy

gooddata-sdk/gooddata_sdk/visualization.py
JIRA: CQ-89
Visualization object filter field setters are required as a part of [CQ-87](https://gooddata.atlassian.net/browse/CQ-87).
[CQ-87]: https://gooddata.atlassian.net/browse/CQ-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> trivial(gooddata-sdk) - Add filters setter to visualization object

.github/actions/hugo-build-action/action.yaml, .github/workflows/netlify-deploy-preview.yaml, scripts/generate.sh
- generate.sh had a problem with parsing master
trivial
=> ci: fix generate.sh bug

.github/actions/hugo-build-action/action.yaml, .github/actions/hugo-build-versioned-action/action.yaml
This PR contains refactoring and removal of the `peaceiris/actions-hugo` action, which is not necessary anymore due to the presence of Go and node, and installation of node dependencies, including extended Hugo.
=> Remove unnecessary `peaceiris/actions-hugo` from hugo build actions

.github/actions/hugo-build-action/action.yaml, .github/actions/hugo-build-versioned-action/action.yaml
It seems that Hugo was not installed by `npm ci` therefore the installation needs to be done explicitly.
=> ci: add hugo installation to actions

gooddata-sdk/gooddata_sdk/visualization.py
It was reported by customer that they would appreciate to have the timeout setting for get_visualization method. We agreed that it would be the best to have this setting for every exposed method. In this first iteration, it is only exposed for this specific method. Note, that we want to add it for other methods in the future, and also add global setting.
JIRA: EB-119
=> fix: allow specifying timeout for get_visualization

gooddata-sdk/gooddata_sdk/compute/model/execution.py
To keep things consistent, we changed the TotalFunction enum value for native totals from NATIVE to NAT on the backend. This is the adaptation to that.
JIRA: CQ-652
risk: low
=> refactor: adapt to the change of NATIVE -> NAT on backend

gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/catalog/filter_by.py, gooddata-sdk/gooddata_sdk/catalog/workspace/content_service.py, gooddata-sdk/tests/catalog/fixtures/workspace_content/label_elements.yaml, gooddata-sdk/tests/catalog/test_catalog_workspace_content.py
…t api
Added `exactFilter` and `filterBy` options for the `collectLabelElement` API. Tests updated accordingly as well. Note: no new catalog type for `exactFilter` as it is just a `List[str]`.
JIRA: LX-432
risk: low
=> feat: Support filterBy and exactFilter options for collectLabelElement API

gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/compute/compute_to_sdk_converter.py, gooddata-sdk/gooddata_sdk/utils.py, gooddata-sdk/gooddata_sdk/visualization.py, gooddata-sdk/tests/compute/__init__.py, gooddata-sdk/tests/compute/test_compute_to_sdk_converter.py
This will be useful in the Flight RPC functions as they will get the execution as a JSON from the server and we want to make them more ergonomic by converting them to the SDK model (e.g. to launch another execution from the SDK).
JIRA: CQ-577
risk: low
=> feat: add convertor from Compute dicts to SDK model

.github/workflows/rw-collect-changes.yaml, .github/workflows/rw-python-tests.yaml, Dockerfile, Makefile, gooddata-flight-server/gooddata_flight_server/__init__.py, gooddata-flight-server/gooddata_flight_server/flexfun/flex_fun_execution_context.py, gooddata-flight-server/setup.py, gooddata-flight-server/tox.ini, gooddata-sdk/gooddata_sdk/catalog/data_source/service.py, gooddata-sdk/gooddata_sdk/catalog/export/request.py, gooddata-sdk/gooddata_sdk/catalog/export/service.py, gooddata-sdk/gooddata_sdk/catalog/organization/service.py, gooddata-sdk/gooddata_sdk/catalog/workspace/service.py, gooddata-sdk/gooddata_sdk/compute/model/filter.py, gooddata-sdk/tests/catalog/test_catalog_user_service.py, pyproject.toml
Allow the users to parse the incoming executionRequest when invoking the Flight RPC function. Use the gooddata-sdk objects so that they can be easily reused in the gooddata-sdk itself.
Also, add the gooddata-flight-server to the CI pipelines, make sure the coverage is published and fix all warnings in the Dockerfile.
Fix some code smells along the way, see the last commit for more details.
JIRA: CQ-577
risk: low
=> feat: add classes to parse executionRequest in Flight RPC

gooddata-flight-server/gooddata_flight_server/flexfun/flex_fun_execution_context.py
The attribute filter values can contain None values so reflect that in the typings appropriately.
JIRA: CQ-743
risk: low
=> fix: type ExecutionContext attribute filter values properly

gooddata-flight-server/gooddata_flight_server/config/config.py, gooddata-flight-server/gooddata_flight_server/server/flight_rpc/flight_middleware.py, gooddata-flight-server/gooddata_flight_server/server/flight_rpc/flight_server.py, gooddata-flight-server/gooddata_flight_server/server/flight_rpc/flight_service.py, gooddata-flight-server/sample-config.toml, gooddata-flight-server/tests/config/sample-config.toml, gooddata-flight-server/tests/config/test_config.py, gooddata-flight-server/tox.ini
- The configs & a lot of code were in place already from day-1
- However, the server did not have proper open telemetry middleware & handling of contexts / spans in the 'core' of the request handling logic
- This is now implemented
- Added new option `otel_extract_context` that influences whether the middleware should extract  & use context coming 'over the wire' in the headers or not. Extracting & using context makes sense when server exports to same backend as its clients -> one can get nice long traces. If this is not the case, then this option should stay off (which is the default) => meaning every Flight RPC call will create new trace id (which the plugged in Flight RPC methods may then access and propagate to whatever calls they make)
Sample config + tests of config updated. The …
=> RELATED: CQ-670 - Implement & tweak OpenTelemetry propagation logic

gooddata-flight-server/gooddata_flight_server/__init__.py
- the create_server, create_flexfun_methods and the server class itself should be exposed
- this is essential for programmatic usage of the infra from the outside
JIRA: CQ-670
=> RELATED: CQ-670 - add forgotten re-exports

gooddata-flight-server/gooddata_flight_server/__init__.py
These make it possible to use the types from the root of the package without delving into the internals.
JIRA: CQ-764
risk: low
=> chore: add missing re-exports

dev-requirements.txt, gooddata-flight-server/tox.ini
Flight server no longer depends on SDK and API client, so let's remove that from tox.
Also add missing dev-requirements.txt entries for Flexfun.
JIRA: CQ-754
risk: low
=> chore: remove flight-server dependencies

gooddata-flexfun/README.md, gooddata-flexfun/gooddata_flexfun/flexfun/flex_fun_execution_context.py, gooddata-flexfun/json_schemas/execution-context/attribute.json, gooddata-flexfun/json_schemas/execution-context/date-granularity.json, gooddata-flexfun/json_schemas/execution-context/execution-context.json, gooddata-flexfun/json_schemas/execution-context/filter.json, gooddata-flexfun/json_schemas/execution-context/label-elements/depends-on-date-filter.json, gooddata-flexfun/json_schemas/execution-context/label-elements/depends-on.json, gooddata-flexfun/json_schemas/execution-context/label-elements/execution-request.json, gooddata-flexfun/test-requirements.txt, gooddata-flexfun/tests/json_schemas/__init__.py, gooddata-flexfun/tests/json_schemas/conftest.py, gooddata-flexfun/tests/json_schemas/test_attribute_schema.py, gooddata-flexfun/tests/json_schemas/test_depends_on_date_filter_schema.py, gooddata-flexfun/tests/json_schemas/test_depends_on_schema.py, gooddata-flexfun/tests/json_schemas/test_execution_context_schema.py, gooddata-flexfun/tests/json_schemas/test_filter_schema.py, gooddata-flexfun/tests/json_schemas/test_label_elements_execution_request_schema.py
Add schemata for the execution requests coming from the server. Does not type the AFM part yet, but all the others are covered. Includes several tests making sure the schemata behave as expected.
Also improve the flexfun README file: link to the much more information-rich template repo.
JIRA: CQ-755, CQ-756
risk: low
=> feat: add JSON schemas for the execution contexts

gooddata-flexfun/gooddata_flexfun/flexfun/flex_fun.py, gooddata-flexfun/gooddata_flexfun/flexfun/flex_fun_task.py, gooddata-flexfun/gooddata_flexfun/flexfun/flight_methods.py, gooddata-flight-server/README.md, gooddata-flight-server/gooddata_flight_server/server/flight_rpc/server_methods.py, gooddata-flight-server/gooddata_flight_server/tasks/task_result.py, gooddata-flight-server/tests/tasks/test_task_executor.py
- Added docs introducing and giving example how to use the TaskExecutor
- Discovered that the infra was missing some common convenience
- Added utilities / convenience methods to create TaskResult from Arrow Table or RecordBatchReader
- Added utility to create FlightDataStream for a task result; this can be used to conveniently implement do_get() when tasks are involved
- Removed some dead todos + clarified contract in FlexFun
=> RELATED: CQ-670 - docs improvements

gooddata-flexfun/gooddata_flexfun/flexfun/flex_fun_execution_context.py
It was replaced by the report- or labelElements-specific versions everywhere, so let's get rid of it.
JIRA: CQ-812
risk: low
=> chore: remove obsolete executionRequest

.github/workflows/build-release.yaml, .github/workflows/dev-release.yaml, gooddata-flexfun/LICENSE.txt
The packages are now ready to be released along the rest of the SDK.
JIRA: CQ-761
risk: low
=> build: add flight-server and flexfun to release

gooddata-pandas/gooddata_pandas/data_access.py
Thanks @no23reason for noticing this. For the case where there are not attributes it is not necessary to get the full catalog.
JIRA: PSDK-205
risk: low
=> fix: call get_full_catalog when necessary

gooddata-sdk/gooddata_sdk/visualization.py
Added `attributeFilterConfigs` to visualization. This holds the display label information when using a secondary label in a filter.
JIRA: LX-379
risk: low
=> feat: add attributeFilterConfig to Visualization

gooddata-sdk/gooddata_sdk/catalog/organization/layout/__init__.py
Missing `__init__.py` file caused `from gooddata_sdk import *` to fail.
JIRA: TRIVIAL
risk: low
=> fix: add missing __init__.py file

gooddata-sdk/gooddata_sdk/catalog/export/request.py, gooddata-sdk/gooddata_sdk/catalog/export/service.py, gooddata-sdk/gooddata_sdk/catalog/organization/layout/notification_channel.py, gooddata-sdk/tests/export/fixtures/test_export_csv_by_visualization_id.yaml, gooddata-sdk/tests/export/fixtures/test_export_excel_by_visualization_id.yaml
It is not necessary to execute visualization and get `execution_result` for `export_tabular_by_visualization_id`. Now export by visualization_id is supported out of the box.
JIRA: TRIVIAL
risk: low
=> fix: export_tabular_by_visualization_id does not need to call afm

gooddata-sdk/gooddata_sdk/compute/service.py
reset chat history
fix output type
=> PoC expose AI use cases

.github/workflows/bump-version.yaml
Since rel/1.14.0 release branches do not contain the commit with version bump. The issue is in workflow that does not guarantee integrity. The workflow uses specific release branch now rel/x.y.z from the beginning and because it is protected branch it will not get deleted. Only patch release has different branch name – we do not want to persist it.
JIRA: PSDK-213
risk: low
=> fix: release does not contain bumped version

.github/workflows/bump-version.yaml, gooddata-sdk/gooddata_sdk/compute/service.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 925e7dbd (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/11774454929).
=> [bot] Merge master/925e7dbd into rel/dev

.github/workflows/bump-version.yaml
=> feat: update commit and push of release commit

gooddata-flexconnect/gooddata_flexconnect/__init__.py
To enable proper type safety in client code, we need to export the "umbrella" ExecutionContextFilter type as well.
JIRA: CQ-893
risk: low
=> chore: add missing export

gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/data_source.py
Had placed `client_id` in the wrong place. Should be part of `CatalogDeclarativeDataSource`
JIRA: LX-669
risk: low
=> fix: client_id was missing from declarative data source

gooddata-dbt/requirements.txt, gooddata-sdk/requirements.txt
Thanks to [issue](https://github.com/gooddata/gooddata-python-sdk/issues/914) for reporting vulnerability CVE-2024-35195 in requests library.
JIRA: TRIVIAL
risk: low
=> chore(requests): bump requests version

gooddata-flexconnect/gooddata_flexconnect/function/flight_methods.py, gooddata-flexconnect/gooddata_flexconnect/function/function_task.py, gooddata-flexconnect/tests/server/conftest.py, gooddata-flexconnect/tests/server/funs/fun1.py, gooddata-flexconnect/tests/server/funs/fun3.py, gooddata-flexconnect/tests/server/test_flexconnect_server.py, gooddata-flight-server/gooddata_flight_server/tasks/thread_task_executor.py
FlexConnect's implementation of GetFlightInfo uses task executor to submit tasks that will invoke the FlexConnect functions. The GetFlightInfo will then wait for the task to complete (generate flight) and return result.
The GetFlightInfo implementation had hardcoded (in a constant) timeout that was used for waiting. This timeout was set to 60 seconds. This can sometimes be too little. And what's worse, it cannot be changed.
This PR introduces new setting `call_deadline_ms` that is expected to appear in the `[flexconnect]` configuration section. It is deadline in milliseconds. The default was bumped to 180 seconds.
---
Part of this PR are two additional changes:
- Try to cancel the task for when the deadline was exceeded. This is basic sanity. The task may be stuck in queue -> cancel will …
=> RELATED: CQ-1005 - make FlexConnect function call deadline configurable

gooddata-sdk/gooddata_sdk/catalog/entity.py
When using token from environment variable or file or client secret from file, not all data sources require base64 encoding, i.e. Databricks does not but BigQuery does. Boolean to encode or not added as optional parameter, with default et to True for token for backwards compatability, but False for client secret since it is new use case.
JIRA: LX-691
risk: low
=> feat: optional base64 encoding for local cred

gooddata-sdk/gooddata_sdk/catalog/entity.py, gooddata-sdk/tests/catalog/test_catalog_data_source.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 61279e3d (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/12690007915).
=> [bot] Merge master/61279e3d into rel/dev

gooddata-pandas/gooddata_pandas/data_access.py, gooddata-pandas/gooddata_pandas/utils.py, gooddata-pandas/tests/utils/__init__.py, gooddata-pandas/tests/utils/fixtures/test_get_catalog_attributes_for_extract.yaml, gooddata-pandas/tests/utils/test_utils.py, gooddata-sdk/gooddata_sdk/utils.py
Improves fetching for catalog attributes. The previous implementation used threshold to prevent `414 Request-URI Too Large`. If the threshold was reached the whole catalog was fetched. The new implementation calls get_attributes_catalog multiple times with different rsql_filter.
JIRA: STL-1036
risk: low
=> perf: smart catalog attributes fetching

gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/data_source.py
client_id field may be empty string, improved check to account for this
JIRA: LX-691
risk: low
=> fix: proper cred loading for Databricks

gooddata-sdk/gooddata_sdk/catalog/data_source/service.py
Missed a spot, same thing:
client_id field may be empty string, improved check to account for this
JIRA: LX-691
risk: low
=> fix: proper cred loading for Databricks pt2.

gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/data_source.py, gooddata-sdk/gooddata_sdk/catalog/data_source/service.py, gooddata-sdk/tests/catalog/test_catalog_data_source.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to d5929bbe (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/13179187007).
=> [bot] Merge master/d5929bbe into rel/dev

docs/layouts/partials/api-ref-function-parenthesis.html, docs/layouts/partials/api-ref-object-partial.html
The api reference code was malformed, with redundant whitespaces at the beginning and whitespaces wrapping parameters.
JIRA: DP-3082
risk: low
=> docs: fix malformed api-ref

.github/workflows/rw-python-tests.yaml, docs/layouts/partials/api-ref-function-parenthesis.html, docs/layouts/partials/api-ref-object-partial.html
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to c4a6afe1 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/13282201892).
=> [bot] Merge master/c4a6afe1 into rel/dev

gooddata-sdk/gooddata_sdk/table.py
When some visualizations (e.g.: Headline) get executed, the resulting data is only 1D (single dimension in resultSpec).
In such cases we want to ask for 1d offsets&limits, even if we explicitly request "always_two_dimensional" table.
risk: low
JIRA: CQ-1105
=> fix: support 1d vis table conversion

gooddata-sdk/gooddata_sdk/catalog/export/service.py
It was necessary to pass metadata to export_pdf; otherwise, an error was raised.
JIRA: TRIVIAL
risk: low
=> fix: export_pdf failed without metadata

gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/compute/model/base.py, gooddata-sdk/gooddata_sdk/compute/model/filter.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 7f747008 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/13988861275).
=> [bot] Merge master/7f747008 into rel/dev

gooddata-sdk/gooddata_sdk/visualization.py
For some reason it could happen that `get_visualization` did not have any `included` and get failed.
JIRA: TRIVIAL
risk: low
=> fix: `get_visualization` failed for missing included

gooddata-flight-server/gooddata_flight_server/errors/error_info.py, gooddata-flight-server/tests/errors/error_info.py
- ErrorInfo is passed as FlightError.extra_info
- In turn, extra_info contents are transported via gRPC headers
- gRPC headers have hard limit of 16kB size (otherwise get gRPC Resource Exhausted: initial metadata too large)
- added code to truncate `msg` and `detail` if necessary. Limits are 256 and 512 chars respectivelly.
JIRA: CQ-1268
=> RELATED: CQ-1268 - add limits to ErrorInfo fields

gooddata-sdk/gooddata_sdk/client.py, gooddata-sdk/gooddata_sdk/compute/model/execution.py, gooddata-sdk/gooddata_sdk/compute/service.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to d08da677 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/14491526901).
=> [bot] Merge master/d08da677 into rel/dev

MAINTENANCE.md
=> docs: clarification in MAINTENANCE.md

gooddata-flexconnect/LICENSE.txt
Reflect the flexfun -> flexconnect rename in both the license file and the symlink.
JIRA: CQ-102
risk: low
=> fix: use the correct LICENSE symlink

gooddata-flexconnect/gooddata_flexconnect/function/flight_methods.py, gooddata-flexconnect/gooddata_flexconnect/function/function_invocation.py, gooddata-flexconnect/tests/server/conftest.py, gooddata-flexconnect/tests/server/funs/fun3.py, gooddata-flexconnect/tests/server/funs/fun4.py, gooddata-flexconnect/tests/server/test_flexconnect_server.py, gooddata-flight-server/gooddata_flight_server/tasks/task_executor.py, gooddata-flight-server/gooddata_flight_server/tasks/thread_task_executor.py
Add a polling mechanism to the FlexConnect functions so that long-running tasks can be polled for and canceled.
The polling is opt-in via a call header: this is to ensure compatibility with GoodData versions that do not support this yet.
The TaskExecutor now supports returning a timestamp of when a particular task was submitted. This is to keep track of the call deadline breaches.
JIRA: CQ-1124
risk: low
=> feat: add support for polling in FlexConnect server

docs/content/en/latest/administration/user-groups/_index.md, docs/content/en/latest/administration/user-groups/get_user_group_permissions.md, docs/content/en/latest/administration/user-groups/manage_user_group_permissions.md, docs/content/en/latest/administration/users-and-user-groups/_index.md, docs/content/en/latest/administration/users-and-user-groups/assign_permissions_bulk.md, docs/content/en/latest/administration/users-and-user-groups/revoke_permissions_bulk.md, docs/content/en/latest/administration/users/_index.md, docs/content/en/latest/administration/users/get_user_permissions.md, docs/content/en/latest/administration/users/manage_user_permissions.md, docs/package-lock.json, gooddata-sdk/gooddata_sdk/catalog/user/service.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 8b87cc9a (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/15492215701).
=> [bot] Merge master/8b87cc9a into rel/dev

gooddata-pandas/gooddata_pandas/data_access.py, gooddata-pandas/gooddata_pandas/dataframe.py, gooddata-pandas/gooddata_pandas/series.py
Users can now provide a callback that will be called with the Execution object as soon as it is available. This is useful for getting some of the information available in the Execution object before the actual data is loaded. The Execution object can also be used to cancel the execution result operation.
Also unify Execution types in data_access.py: no need to use the ExecutionResponse alias anymore.
JIRA: CQ-1387
risk: low
=> feat: add on_execution_submitted to gooddata_pandas

gooddata-pandas/gooddata_pandas/good_pandas.py, gooddata-sdk/gooddata_sdk/catalog/filter_by.py
mypy in some cases complains about `_dict_to_filter_by` and GoodDataSdk initialization in GoodPandas.
JIRA: TRIVIAL
risk: low
=> fix: mypy findings

.github/workflows/build-release.yaml, .github/workflows/dev-release.yaml
=> chore: fix gh-action-pypi-publish version

docs/content/en/latest/workspace-content/analytics-model/store_analytics_model_to_disk.md, docs/content/en/latest/workspace-content/logical-data-model/store_ldm_to_disk.md, gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/data_source.py, gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/physical_model/table.py, gooddata-sdk/gooddata_sdk/catalog/user/declarative_model/user.py, gooddata-sdk/gooddata_sdk/catalog/user/declarative_model/user_group.py, gooddata-sdk/gooddata_sdk/catalog/workspace/content_service.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/analytics_model/analytics_model.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/analytics_model/base.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/logical_model/dataset/dataset.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/logical_model/dataset_extensions/dataset_extension.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/logical_model/date_dataset/date_dataset.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/logical_model/ldm.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/workspace.py, gooddata-sdk/gooddata_sdk/catalog/workspace/service.py, gooddata-sdk/gooddata_sdk/utils.py
While storing workspace content on GitHub it is useful to have sorted content of YAML files. Therefore, the sort option is added. It is set to False because of backward compatibility.
JIRA: PSDK-220
risk: low
=> feat: add option to sort before store

gooddata-sdk/gooddata_sdk/client.py, gooddata-sdk/gooddata_sdk/sdk.py
Add certificate support to GoodDataSdk initialization.
JIRA: PSDK-222
risk: low
=> feat: add certificate support
