gooddata-fdw/docs/requirements.txt, gooddata-fdw/tox.ini, gooddata-pandas/docs/requirements.txt, gooddata-pandas/tox.ini, gooddata-sdk/docs/requirements.txt, gooddata-sdk/tox.ini
readthedocs expects one project in the repository so it is not able to
install just e.g. gooddata-sdk. Install it with help of requirements.txt
=> NAS-2918 make docs build compatible with rtd

CONTRIBUTING.md, MAINTENANCE.md
New documentation file MAINTENENCE created to cover repo release and
maintenance documentation.
=> NAS-2918 document readthedocs integration

gooddata-fdw/docs/installation.rst
Extended FDW documentation added use case when user has running GoodData.CN instance.
=> NAS-3063 Extended FDW documentation

gooddata-sdk/docs/services.rst
Fixed typo in data soruce service code snippet
=> Fixed typo in data soruce service code snippet

gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/catalog/workspace/service.py, gooddata-sdk/tests/catalog/fixtures/workspaces/demo_catalog_list_attributes.json, gooddata-sdk/tests/catalog/fixtures/workspaces/demo_catalog_list_facts.json, gooddata-sdk/tests/catalog/fixtures/workspaces/demo_catalog_list_labels.json, gooddata-sdk/tests/catalog/fixtures/workspaces/demo_catalog_list_metrics.json, gooddata-sdk/tests/catalog/test_catalog_workspace.py
Fixed path in load_and_put_declarative_ldm and load_and_put_declarative_analytics_model.
Added objects in __init__.py.
Added new methods for listing attributes, facts, metrics.
=> NAS-3215 extended CatalogWorkspaceContentService + fix __init__

.github/workflows/tests.yaml, README.md, gooddata-fdw/tox.ini, gooddata-pandas/tox.ini, gooddata-sdk/tox.ini
Added badges in README.md and added support for code coverage using codecov.io
=> NAS-3236 added badges in README.md

.github/workflows/tests.yaml, gooddata-sdk/gooddata_sdk/catalog/workspace/service.py
Trigger tests.yaml when pushed to master
=> NAS-3236_workflow_change

.pre-commit-config.yaml, fmt-requirements.txt, gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/data_source.py, gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/physical_model/column.py, gooddata-sdk/gooddata_sdk/catalog/data_source/entity_model/data_source.py, gooddata-sdk/gooddata_sdk/catalog/data_source/service.py, gooddata-sdk/gooddata_sdk/catalog/workspace/entity_model/workspace.py, gooddata-sdk/tests/catalog/expected/declarative_data_sources.json, gooddata-sdk/tests/catalog/fixtures/data_sources/demo_delete_declarative_data_sources.json, gooddata-sdk/tests/catalog/fixtures/data_sources/demo_load_and_put_declarative_data_sources.json, gooddata-sdk/tests/catalog/fixtures/data_sources/demo_put_declarative_data_sources.json, gooddata-sdk/tests/catalog/fixtures/data_sources/demo_put_declarative_data_sources_connection.json, gooddata-sdk/tests/catalog/fixtures/data_sources/demo_store_declarative_data_sources.json, gooddata-sdk/tests/catalog/fixtures/data_sources/demo_test_declarative_data_sources.json, gooddata-sdk/tests/catalog/load/data_source_credentials/data_sources_credentials.yaml, gooddata-sdk/tests/catalog/load/declarative_data_sources/demo-bigquery-ds.yaml, gooddata-sdk/tests/catalog/load/declarative_data_sources/demo-test-ds.yaml, gooddata-sdk/tests/catalog/load/declarative_data_sources/demo-vertica-ds.yaml, gooddata-sdk/tests/catalog/test_catalog_data_source.py
Added methods put, load, and store.
=> NAS-3461 completion of declarative data sources

gooddata-sdk/gooddata_sdk/sdk.py, gooddata-sdk/gooddata_sdk/support.py, gooddata-sdk/mypy.ini, gooddata-sdk/tests/support/__init__.py, gooddata-sdk/tests/support/fixtures/is_available.json, gooddata-sdk/tests/support/fixtures/is_available_no_access.json, gooddata-sdk/tests/support/fixtures/wait_till_available_no_wait.json, gooddata-sdk/tests/support/test_support.py
Two availability methods added. One for check GD.CN is up, another for
wait till GD.CN is up.
=> NAS-3548 add SupportService with availability methods

gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/logical_model/ldm.py, gooddata-sdk/tests/catalog/fixtures/workspaces/demo_load_and_modify_ds_and_put_declarative_ldm.json, gooddata-sdk/tests/catalog/test_catalog_workspace_content.py, gooddata-sdk/tests/gd_test_config.yaml
Purpose is to change target data source or to put the same LDM into different workspace/org, where different data source exists with the same model.
=> NAS-3652: Enable modifying mapped data source in LDM

gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/catalog/data_source/validation/__init__.py, gooddata-sdk/gooddata_sdk/catalog/data_source/validation/data_source.py, gooddata-sdk/gooddata_sdk/catalog/workspace/service.py, gooddata-sdk/tests/catalog/fixtures/workspaces/demo_load_and_modify_ds_and_put_declarative_ldm.json, gooddata-sdk/tests/catalog/test_catalog_workspace_content.py
In methods put_declarative_ldm, and load_and_put_declarative_ldm added optional parameter validator, which validates data source ids in ldm.
=> NAS-3677 add data source id validators for ldm

gooddata-sdk/docs/services/catalog-data-source.rst, gooddata-sdk/docs/services/catalog-workspace-content.rst, gooddata-sdk/docs/services/catalog-workspace.rst
Added scan PDM for catalog-data-source.rst + fixed default for layout_root_path
Added validator for catalog-workspace-content.rst + fixed default for layout_root_path
Typo fixed for catalog-workspace.rst + fixed default for layout_root_path
=> NAS-3694 finalizing documentation for release

gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/catalog/data_source/entity_model/data_source.py, gooddata-sdk/tests/catalog/fixtures/data_sources/vertica.json, gooddata-sdk/tests/catalog/test_catalog_data_source.py
Do not force developers to use PostgresAttributes and always have to override the port.
=> NAS-3673: Provide dedicated VerticaAttributes

gooddata-sdk/gooddata_sdk/catalog/base.py, gooddata-sdk/gooddata_sdk/catalog/data_source/action_requests/ldm_request.py, gooddata-sdk/gooddata_sdk/catalog/data_source/action_requests/scan_model_request.py, gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/data_source.py, gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/physical_model/column.py, gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/physical_model/pdm.py, gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/physical_model/table.py, gooddata-sdk/gooddata_sdk/catalog/identifier.py, gooddata-sdk/gooddata_sdk/catalog/permissions/permission.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/analytics_model/analytics_model.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/logical_model/dataset/dataset.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/logical_model/date_dataset/date_dataset.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/logical_model/ldm.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/workspace.py, gooddata-sdk/requirements.txt, gooddata-sdk/setup.py, gooddata-sdk/test-requirements.txt, gooddata-sdk/type-requirements.txt
* classes uses attrs and cattrs which should make development easier in the future
* alias @attr.s was used because IntelliJ supports hinting for that when it supports new aliases such as define, the new aliases will be used
=> NAS-3782 reimplemented declarative classes with attrs and cattrs

gooddata-pandas/gooddata_pandas/data_access.py, gooddata-pandas/tests/dataframe/fixtures/empty_indexed_dataframe.json, gooddata-pandas/tests/dataframe/fixtures/empty_not_indexed_dataframe.json, gooddata-pandas/tests/dataframe/test_indexed_dataframe.py, gooddata-pandas/tests/dataframe/test_not_indexed_dataframe.py
* fixed IndexError when a user wanted to get a dataframe consisting of columns that did not yield any results
=> NAS-2884 fixed empty dataframe

gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/catalog/user/declarative_model/user_and_user_groups.py, gooddata-sdk/gooddata_sdk/catalog/user/service.py, gooddata-sdk/tests/catalog/fixtures/users/get_declarative_users_user_groups.json, gooddata-sdk/tests/catalog/fixtures/users/load_and_put_declarative_users_user_groups.json, gooddata-sdk/tests/catalog/fixtures/users/put_declarative_users_user_groups.json, gooddata-sdk/tests/catalog/fixtures/users/store_declarative_users_user_groups.json, gooddata-sdk/tests/catalog/test_catalog_user_service.py
* extended CatalogUser service with UsersAndUserGroups REST APIs calls
* added test support for new features
=> NAS-4034 add UsersAndUserGroups support

gooddata-pandas/gooddata_pandas/__init__.py
to allow typechecking in clients
=> XSH-783 Export type for label_overrides

gdc_fossa.yaml
=> Update image for fossa scanning

gooddata-sdk/gooddata_sdk/catalog/data_source/entity_model/data_source.py, gooddata-sdk/gooddata_sdk/catalog/data_source/service.py, gooddata-sdk/tests/catalog/fixtures/data_sources/bigquery.yaml, gooddata-sdk/tests/catalog/fixtures/data_sources/demo_load_and_put_declarative_data_sources.yaml, gooddata-sdk/tests/catalog/fixtures/data_sources/demo_register_upload_notification.yaml, gooddata-sdk/tests/catalog/fixtures/data_sources/demo_store_and_load_and_put_declarative_pdm.yaml, gooddata-sdk/tests/catalog/fixtures/data_sources/demo_store_declarative_data_sources.yaml, gooddata-sdk/tests/catalog/fixtures/data_sources/dremio.yaml, gooddata-sdk/tests/catalog/fixtures/data_sources/patch.yaml, gooddata-sdk/tests/catalog/fixtures/data_sources/redshift.yaml, gooddata-sdk/tests/catalog/fixtures/data_sources/snowflake.yaml, gooddata-sdk/tests/catalog/fixtures/data_sources/test_create_update.yaml, gooddata-sdk/tests/catalog/fixtures/data_sources/vertica.yaml, gooddata-sdk/tests/catalog/test_catalog_data_source.py
* added parameters and decoded_parameters to CatalogDataSource
* minor fix
=> PSDK-103 Adapt entity data source

gooddata-fdw/Dockerfile
* added installation of a new API client
=> PSDK-111 Update Dockerfile for GoodData FDW

.gitignore, gooddata-sdk/docs/hugo/docs/assets/scss/_styles_project.scss, gooddata-sdk/docs/hugo/docs/assets/scss/parameter.scss, gooddata-sdk/docs/hugo/docs/assets/scss/parameters-block.scss, gooddata-sdk/docs/hugo/docs/content/en/docs/_index.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/_index.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/create_or_update_data_source.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/delete_data_source.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/generate_logical_model.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/get_data_source.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/get_declarative_data_sources.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/list_data_source_tables.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/list_data_sources.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/load_and_put_declarative_data_sources.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/load_declarative_data_sources.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/patch_data_source_attributes.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/put_declarative_data_sources.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/register_upload_notification.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/scan_data_source.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/scan_schemata.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/store_declarative_data_sources.md, gooddata-sdk/docs/hugo/docs/content/en/docs/data/data-source/test_data_sources_connection.md, gooddata-sdk/docs/hugo/docs/content/en/docs/getting-started.md, gooddata-sdk/docs/hugo/docs/layouts/partials/navbar.html, gooddata-sdk/docs/hugo/docs/layouts/shortcodes/parameter.html, gooddata-sdk/docs/hugo/docs/layouts/shortcodes/parameters-block.html, gooddata-sdk/gooddata_sdk/catalog/data_source/service.py
Please do not merge this Pull Request.
=> DP-2330 Data Sources documentation

gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/logical_model/ldm.py, gooddata-sdk/tests/catalog/test_catalog_workspace_content.py
=> PSDK-129: Allow chaining of extension methods in DeclarativeModel

Makefile, gooddata-sdk/docs/hugo/docs/content/en/docs/workspace/workspaces/put_declarative_workspace.md
* add new docs build Makefile command
=> TRIVIAL: Fix wrong code snippet

gooddata-sdk/gooddata_sdk/compute/model/attribute.py, gooddata-sdk/gooddata_sdk/insight.py, gooddata-sdk/tests/compute_model/afm/attribute_showAllValues_False.snapshot.json, gooddata-sdk/tests/compute_model/afm/attribute_showAllValues_True.snapshot.json, gooddata-sdk/tests/compute_model/test_compute_model.py, gooddata-sdk/tests/insight/resources/one_metric_date_attribute_show_all_values.json, gooddata-sdk/tests/insight/snapshots/one_metric_date_attribute_show_all_values.snapshot.json, gooddata-sdk/tests/table/fixtures/table_with_attribute_show_all_values.yaml, gooddata-sdk/tests/table/test_table.py, scripts/generate.sh
With the improvement, it is possible to:
- execute AFM requests with showAllValues
- execute insights stored with showAllValues
=> CAL-765: add support for showAllValues

gooddata-pandas/gooddata_pandas/good_pandas.py, gooddata-pandas/tests/good_pandas/__init__.py, gooddata-pandas/tests/good_pandas/profiles/profiles.yaml, gooddata-pandas/tests/good_pandas/test_good_pandas.py, gooddata-sdk/gooddata_sdk/utils.py, gooddata-sdk/tests/sdk/test_sdk.py
Load credentials for GoodPandas from the config file
=> PSDK-123 GoodPandas classmethod to load credentials from config file

gooddata-sdk/gooddata_sdk/catalog/user/entity_model/user.py, gooddata-sdk/tests/catalog/fixtures/users/test_user_add_user_group.yaml, gooddata-sdk/tests/catalog/fixtures/users/test_user_add_user_groups.yaml, gooddata-sdk/tests/catalog/fixtures/users/test_user_remove_user_groups.yaml, gooddata-sdk/tests/catalog/fixtures/users/test_user_replace_user_groups.yaml, gooddata-sdk/tests/catalog/test_catalog_user_service.py
Extend CatalogUser methods with user groups manipulation
* add user group
* add user groups
* replace user groups
* remove_user_groups
=> PSDK-138 Extend CatalogUser methods with user groups manipulation

project_common.mk
Fix old linter reference in project_common.mk
=> TRIVIAL: change old linter referrence

CONTRIBUTING.md, Makefile, docs/content/en/docs/getting-started.md, docs/content/en/docs/installation.md, docs/content/en/docs/workspace/workspaces/_index.md, docs/content/en/docs/workspace/workspaces/clone_workspace.md, gooddata-sdk/gooddata_sdk/catalog/data_source/service.py, gooddata-sdk/gooddata_sdk/catalog/user/entity_model/user.py, gooddata-sdk/gooddata_sdk/catalog/user/service.py, gooddata-sdk/gooddata_sdk/catalog/workspace/service.py, gooddata-sdk/gooddata_sdk/sdk.py, gooddata-sdk/gooddata_sdk/utils.py
Updating the docstrings and adding documentation for clone_workspace
Resolving PSDK-137
=> DP-2415 update documentation for 1.3 release

.github/actions/hugo-build-versioned-action/action.yaml, .github/workflows/hugo-docs.yaml, .github/workflows/hugo-versioned-docs.yaml
=> TRIVIAL: Adding -f option to rm, to not throw errors

gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/catalog/workspace/content_service.py, gooddata-sdk/gooddata_sdk/catalog/workspace/model_container.py, gooddata-sdk/gooddata_sdk/insight.py
Extend model containers with missing properties.
Allow using model_container without embedded validObjects function, so it can be cached(pickled) by Streamlit
=> Various improvements for Streamlit demo

gooddata-sdk/gooddata_sdk/catalog/export/service.py
Using custom_override in export_tabular_by_insight_id was inconvenient because exec_table contained generated local ids making custom override not developer friendly. Therefore, I decided to remove the custom override option for now and add it as a part of the follow-up.
=> RELATED: PSDK-148 remove custom_override from export_tabular_by_insight_id

gooddata-dbt/gooddata_dbt/dbt/cloud.py, gooddata-dbt/gooddata_dbt/dbt_plugin.py
Plus add corresponding logging
=> TRIVIAL: gooddata-dbt - fix env var name for source merge request branch

.github/actions/hugo-build-versioned-action/action.yaml, .github/workflows/tests.yaml
- remove the not existing caching path
- add caching for Python dependency in the docs build
=> TRIVIAL: minor workflows improvement

.github/actions/merge/action.yaml
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 0b162bcf (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/6970396997).
=> [bot] Merge master/0b162bcf into rel/dev

.github/actions/merge/action.yaml, .github/workflows/rel-dev-back-merge.yaml
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 64c0f811 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/6970505026).
=> [bot] Merge master/64c0f811 into rel/dev

gooddata-pandas/gooddata_pandas/result_convertor.py, gooddata-pandas/tests/dataframe/test_dataframe_for_exec_def.py
- added row/col grand totals sum into DF
- added grand total metrics labels into DF (used when metrics in rows)
JIRA: UNI-592
=> Support more use cases in DF result

gooddata-dbt/gooddata_dbt/dbt/base.py, gooddata-dbt/gooddata_dbt/dbt/tables.py
Plus fix titles and tags of generated LDM date dimensions
=> PSDK-162: Adopt missing LDM dataset props 

.github/workflows/bump-version.yaml, MAINTENANCE.md
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 3c8c0641 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/7276272169).
=> [bot] Merge master/3c8c0641 into rel/dev

MAINTENANCE.md, gooddata-sdk/gooddata_sdk/catalog/base.py, gooddata-sdk/gooddata_sdk/catalog/workspace/service.py, gooddata-sdk/tests/catalog/fixtures/workspaces/user_data_filters_for_user_group.yaml, gooddata-sdk/tests/catalog/test_catalog_workspace.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to f890aaf9 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/7276942850).
=> [bot] Merge master/f890aaf9 into rel/dev

docs/content/en/docs/execution/exports/export_tabular.md
Fixing wrong parameters for export_tabular method
=> TRIVIAL: fix docu

.github/workflows/netlify-deploy-preview.yaml
=> CONFIG: INFRA-3308 Consolidate netlify site-id and token

gooddata-pandas/gooddata_pandas/result_convertor.py
=> fix(gooddata-pandas): Process total of grandtotals just once

gooddata-dbt/gooddata_dbt/utils.py, scripts/next_dev.sh
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 8ac0edb2 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/7539037543).
=> [bot] Merge master/8ac0edb2 into rel/dev

gooddata-dbt/gooddata_dbt/utils.py
The related env variable can be set to empty string or even some non-numeric text
=> gooddata-dbt - improve validation of PR number

gooddata-dbt/gooddata_dbt/utils.py, scripts/next_dev.sh
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 506d1e58 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/7539874700).
=> [bot] Merge master/506d1e58 into rel/dev

gooddata-dbt/gooddata_dbt/dbt/cloud.py, gooddata-dbt/gooddata_dbt/dbt/environment.py, gooddata-dbt/gooddata_dbt/dbt_plugin.py
Switch from v2 to v3 API
Read DB_NAME from correct place
Simply the transformation from Environment to profiles.yml
=> gooddata-dbt - fix reading environment from dbt Cloud

gooddata-dbt/gooddata_dbt/dbt_plugin.py
from LDM to analytics phase
before localized workspaces where provisioned only with LDM before analytics was published to source workspaces
=> TRIVIAL: move provisioning of localized workspaces

docs/content/en/docs/administration/permissions/manage_dashboard_permissions.md
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 9c0dbfca (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/7989089832).
=> [bot] Merge master/9c0dbfca into rel/dev

docs/config/production/params.toml, docs/content/en/docs/administration/permissions/manage_dashboard_permissions.md, docs/go.mod, docs/go.sum
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 64ea0a08 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/7991210509).
=> [bot] Merge master/64ea0a08 into rel/dev

.github/actions/hugo-build-action/action.yaml
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 015609c2 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/8005770537).
=> [bot] Merge master/015609c2 into rel/dev

gooddata-sdk/gooddata_sdk/insight.py
=> feature(py-sdk): Allow changing Insight filters

gooddata-sdk/gooddata_sdk/table.py
=> refactor(gooddata-sdk) - Switch up function definitions ordering

gooddata-sdk/gooddata_sdk/table.py, gooddata-sdk/gooddata_sdk/visualization.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 36155e77 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/8206743803).
=> [bot] Merge master/36155e77 into rel/dev

gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/data_source.py, gooddata-sdk/gooddata_sdk/catalog/data_source/entity_model/data_source.py, gooddata-sdk/tests/catalog/fixtures/data_sources/demo_cache_strategy.yaml, gooddata-sdk/tests/catalog/test_catalog_data_source.py
We could not enable the value_in_allowed validation, because the field is optional. This will be revisited later.
=> RELATED: CQ-275 add support for cache_strategy property

gooddata-sdk/gooddata_sdk/catalog/export/service.py, gooddata-sdk/gooddata_sdk/catalog/permission/service.py, gooddata-sdk/gooddata_sdk/catalog/user/management_model/management.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/analytics_model/analytics_model.py, gooddata-sdk/gooddata_sdk/catalog/workspace/service.py, scripts/docs/json_builder.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 399f35b7 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/8262589263).
=> [bot] Merge master/399f35b7 into rel/dev

gooddata-sdk/gooddata_sdk/catalog/workspace/service.py, gooddata-sdk/gooddata_sdk/compute/model/base.py, gooddata-sdk/gooddata_sdk/compute/model/filter.py, gooddata-sdk/gooddata_sdk/visualization.py, gooddata-sdk/tests/compute_model/test_date_filters.py
Allow locales formatting of AbsoluteDateFilter when `icu` package is installed.
JIRA: CQ-95
=> feature(gooddata-sdk): Add locales support for AbsoluteDateFilter

gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/compute/model/filter.py, gooddata-sdk/gooddata_sdk/visualization.py, gooddata-sdk/tests/compute_model/test_metric_value_filter.py
- required for filter description
JIRA: CQ-299
=> fix(py-sdk): Add noop AllMetricValueFilter

gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/catalog/depends_on.py, gooddata-sdk/gooddata_sdk/catalog/workspace/content_service.py, gooddata-sdk/tests/catalog/fixtures/workspace_content/label_elements.yaml, gooddata-sdk/tests/catalog/test_catalog_workspace_content.py
=> feature(gooddata-sdk): support date filters for get elements

.github/workflows/netlify-deploy-preview.yaml
Default GH runners are getting out of memory
=> TRIVIAL: Run htmltest action on larger runner

.github/actions/hugo-build-action/action.yaml, docs/content/en/docs/administration/permissions/put_declarative_permissions.md
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 5aad29e5 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/8643940741).
=> [bot] Merge master/5aad29e5 into rel/dev

.github/workflows/pre-merge.yaml, .github/workflows/rw-collect-changes.yaml, .github/workflows/rw-python-tests.yaml, docs/content/en/docs/administration/permissions/put_declarative_permissions.md
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 9634ed5e (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/8661738629).
=> [bot] Merge master/9634ed5e into rel/dev

.github/actions/hugo-build-action/action.yaml
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 34534b2e (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/8687765423).
=> [bot] Merge master/34534b2e into rel/dev

.github/actions/hugo-build-action/action.yaml, gooddata-sdk/gooddata_sdk/visualization.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to ba73da88 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/8688468661).
=> [bot] Merge master/ba73da88 into rel/dev

.github/actions/hugo-build-action/action.yaml, .github/workflows/pre-merge.yaml
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 03a03bfe (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/8689822956).
=> [bot] Merge master/03a03bfe into rel/dev

.github/workflows/bump-version.yaml, docs/content/en/docs/workspace-content/workspace-content/get_visualization.md
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 9a91344a (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/8737296243).
=> [bot] Merge master/9a91344a into rel/dev

.github/workflows/bump-version.yaml
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 9edf6287 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/8737559452).
=> [bot] Merge master/9edf6287 into rel/dev

docs/content/en/docs/administration/permissions/put_declarative_organization_permissions.md, docs/layouts/404.html, docs/layouts/partials/hooks/body-end.html, docs/static/js/404-old-version.js
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 96b5fcec (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/8798767798).
=> [bot] Merge master/96b5fcec into rel/dev

docs/static/js/404-old-version.js
- added regex to match the version in url no matter the pattern of the url
JIRA: DP-2808
=> DP-2808: fixed the script to show corresponding 404 message

docs/static/js/404-old-version.js, gooddata-pandas/gooddata_pandas/result_convertor.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to c8d7c212 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/8812239298).
=> [bot] Merge master/c8d7c212 into rel/dev

gooddata-sdk/gooddata_sdk/catalog/export/request.py
=> feat: add HTML and PDF to supported formats for tabular exports

gooddata-sdk/gooddata_sdk/table.py
In case a table with no row attributes is received, it is incorrectly assumed to be a non-table ("non-pivot") visualization.
There doesn't seem to be a nice way to figure out whether a viz is table or not. So for now we can try to parse it out from the visualizationUrl field if present.
JIRA: CQ-440
=> fix(gooddata-sdk): add additional vis table type detection condition

gooddata-sdk/gooddata_sdk/catalog/export/request.py, gooddata-sdk/gooddata_sdk/table.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 8242f73d (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/8991399139).
=> [bot] Merge master/8242f73d into rel/dev

.github/workflows/pre-merge.yaml, .github/workflows/rel-dev-back-merge.yaml, .github/workflows/rw-collect-changes.yaml
=> INFRA-3534: rollout ARC github-runner - infra1-small

.github/workflows/pre-merge.yaml, .github/workflows/rel-dev-back-merge.yaml, .github/workflows/rw-collect-changes.yaml, scripts/generate.sh
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to c0626b8b (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/9208298140).
=> [bot] Merge master/c0626b8b into rel/dev

CONTRIBUTING.md, README.md, gooddata-dbt/gooddata_dbt/gooddata/api_wrapper.py, gooddata-pandas/docs/examples.rst, gooddata-pandas/gooddata_pandas/dataframe.py, gooddata-sdk/README.md, gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/catalog/export/service.py, gooddata-sdk/gooddata_sdk/sdk.py, gooddata-sdk/gooddata_sdk/table.py, gooddata-sdk/gooddata_sdk/visualization.py, gooddata-sdk/tests/overview.md
=> feat: remove deprecated occurrence of `insight`

docs/content/en/latest/workspace-content/localization/_index.md, docs/content/en/latest/workspace-content/localization/add_metadata_locale.md, docs/content/en/latest/workspace-content/localization/clean_metadata_localization.md, docs/content/en/latest/workspace-content/localization/get_metadata_localization.md, docs/content/en/latest/workspace-content/localization/save_metadata_locale_to_disk.md, docs/content/en/latest/workspace-content/localization/set_metadata_locale_from_disk.md, docs/content/en/latest/workspace-content/localization/set_metadata_localization.md, gooddata-sdk/gooddata_sdk/catalog/workspace/service.py, gooddata-sdk/gooddata_sdk/client.py, gooddata-sdk/gooddata_sdk/utils.py, gooddata-sdk/mypy.ini, gooddata-sdk/requirements.txt, gooddata-sdk/setup.py
- Adding PythonSDK support for Translations
=> STL-169: Translations PySDK support

gooddata-sdk/gooddata_sdk/catalog/workspace/service.py, gooddata-sdk/tests/catalog/fixtures/workspaces/add_metadata_locale.yaml, gooddata-sdk/tests/catalog/fixtures/workspaces/clean_metadata_locale.yaml, gooddata-sdk/tests/catalog/fixtures/workspaces/get_metadata_localization.yaml, gooddata-sdk/tests/catalog/fixtures/workspaces/set_metadata_localization.yaml, gooddata-sdk/tests/catalog/test_catalog_workspace.py, tests-support/tests_support/vcrpy_utils.py
- Adding tests for Localization methods
- Does not include cassetes, as they need to be tweaked
JIRA: STL-169
=> feat: Add tests for Localization methods

.github/workflows/netlify-deploy-preview.yaml, gooddata-sdk/gooddata_sdk/catalog/workspace/service.py, gooddata-sdk/tests/catalog/fixtures/workspaces/add_metadata_locale.yaml, gooddata-sdk/tests/catalog/fixtures/workspaces/clean_metadata_locale.yaml, gooddata-sdk/tests/catalog/fixtures/workspaces/get_metadata_localization.yaml, gooddata-sdk/tests/catalog/fixtures/workspaces/set_metadata_localization.yaml, gooddata-sdk/tests/catalog/test_catalog_workspace.py, tests-support/tests_support/vcrpy_utils.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to fbdd7772 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/9466522612).
=> [bot] Merge master/fbdd7772 into rel/dev

docker-compose.yaml, gooddata-dbt/gooddata_dbt/dbt/profiles.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to c308b1b2 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/9756857981).
=> [bot] Merge master/c308b1b2 into rel/dev

docker-compose.yaml, gooddata-dbt/gooddata_dbt/dbt/profiles.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to f1f0dae7 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/9762325689).
=> [bot] Merge master/f1f0dae7 into rel/dev

docs/Dockerfile, docs/content/en/latest/workspace-content/workspace-content/_index.md, docs/content/en/latest/workspace-content/workspace-content/get_visualization.md
=> [master] fix: missing documentation for get_visualization

docs/Dockerfile, docs/content/en/latest/workspace-content/workspace-content/_index.md, docs/content/en/latest/workspace-content/workspace-content/get_visualization.md
=> [1.22.0] fix: missing documentation for get_visualization

.envrc, gooddata-sdk/bin/gdc, gooddata-sdk/gooddata_sdk/catalog/data_source/service.py, gooddata-sdk/gooddata_sdk/catalog/user/declarative_model/user.py, gooddata-sdk/gooddata_sdk/cli/__init__.py, gooddata-sdk/gooddata_sdk/cli/clone.py, gooddata-sdk/gooddata_sdk/cli/constants.py, gooddata-sdk/gooddata_sdk/cli/deploy.py, gooddata-sdk/gooddata_sdk/cli/gdc_core.py, gooddata-sdk/gooddata_sdk/cli/package.json, gooddata-sdk/gooddata_sdk/cli/utils.py, gooddata-sdk/gooddata_sdk/utils.py, gooddata-sdk/setup.py
This is an **EXPERIMENTAL** feature presenting integration with Node.js CLI @gooddata/code-cli. It installs locally Node.js in `~/.gooddata` and utilizes its workspace management.
=> Integration with @gooddata/code-cli

gooddata-sdk/setup.py
=> fix: add missing package.json to .whl

gooddata-flight-server/gooddata_flight_server/__init__.py, gooddata-flight-server/gooddata_flight_server/py.typed, gooddata-flight-server/gooddata_flight_server/tasks/task.py, gooddata-flight-server/setup.py, pyproject.toml
- Corrected setup py -> include script + mark as beta
- added typed marker
- established public API for the new package -> re-exports from the root level __init__.py
=> RELATED: CQ-555 - Tweaks & fixes in the new package

gooddata-flight-server/MANIFEST.in, gooddata-flight-server/setup.py
- setup / manifest were not configured properly
- the file was missing -> server would not start in default configuration
JIRA: CQ-555
=> fix: include logging ini file in built wheel

docs/Dockerfile, docs/content/en/latest/data/data-source/_index.md, gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/data_source.py, gooddata-sdk/gooddata_sdk/catalog/data_source/entity_model/data_source.py, gooddata-sdk/gooddata_sdk/catalog/entity.py, gooddata-sdk/tests/catalog/fixtures/data_sources/snowflake.yaml, gooddata-sdk/tests/catalog/test_catalog_data_source.py
This implements the feature request requested in the following [GitHub issue](https://github.com/gooddata/gooddata-python-sdk/issues/723).
=> Add key pair auth for Snowflake support

gooddata-sdk/gooddata_sdk/compute/model/execution.py, gooddata-sdk/gooddata_sdk/table.py
Properly support the native totals in executions and in tables.
JIRA: CQ-633
risk: low
=> feat: add support for native totals

gooddata-sdk/gooddata_sdk/compute/model/execution.py, gooddata-sdk/gooddata_sdk/table.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to fd8e2b35 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/10107407549).
=> [bot] Merge master/fd8e2b35 into rel/dev

.github/workflows/build-release.yaml
=> feat: Slack notification after successful release

.github/workflows/build-release.yaml, gooddata-sdk/gooddata_sdk/compute/model/execution.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to ba9e2fa3 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/10111401465).
=> [bot] Merge master/ba9e2fa3 into rel/dev

gooddata-flight-server/gooddata_flight_server/flexfun/flex_fun_registry.py, gooddata-flight-server/gooddata_flight_server/flexfun/flex_fun_task.py, gooddata-flight-server/gooddata_flight_server/flexfun/flight_methods.py, gooddata-flight-server/setup.py
- logging improvements
- small fix in do_get handling; iterable of results was not handled 100% correct -> no big deal because flexfun impl cannot return iterable. still, the contract on top of it supports Iterable results. those need to be wrapped into PyArrow GeneratorStream
=> RELATED: CQ-555 - small improvements in flex funs implementation

gooddata-flight-server/setup.py, pyproject.toml
=> chore: add gooddata-flight-server to tbump config

gooddata-sdk/tox.ini
=> refactor: remove py38 from tox envlist

gooddata-dbt/gooddata_dbt/dbt/metrics.py, gooddata-dbt/gooddata_dbt/dbt/tables.py, gooddata-dbt/gooddata_dbt/dbt_plugin.py, gooddata-flight-server/gooddata_flight_server/tasks/temporal_container.py, gooddata-flight-server/tests/server/conftest.py, gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/data_source.py, gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/physical_model/pdm.py, gooddata-sdk/gooddata_sdk/catalog/permission/service.py, gooddata-sdk/gooddata_sdk/catalog/user/declarative_model/user.py, gooddata-sdk/gooddata_sdk/catalog/user/declarative_model/user_group.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/logical_model/ldm.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/workspace.py, gooddata-sdk/gooddata_sdk/catalog/workspace/service.py, gooddata-sdk/gooddata_sdk/utils.py, gooddata-sdk/tests/catalog/test_catalog_data_source.py, gooddata-sdk/tests/catalog/test_catalog_permission.py, pyproject.toml, scripts/docs/json_builder.py
=> feat: utilize all PERF rules

docker-compose.yaml
=> chore: enable rollup totals in pysdk aio d-c

docker-compose.yaml, gooddata-flight-server/gooddata_flight_server/flexfun/flex_fun_execution_context.py, gooddata-flight-server/setup.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to b924897a (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/10508674361).
=> [bot] Merge master/b924897a into rel/dev

gooddata-flight-server/tox.ini
=> chore: missing dependency for tox

gooddata-flight-server/gooddata_flight_server/flexfun/flex_fun_execution_context.py
Reflects the changes done on the backend so that the FlightRPC function gets more information about the filters used in the execution.
JIRA: CQ-577
risk: low
=> feat: add support for ExecutionContextFilters

gooddata-flight-server/gooddata_flight_server/flexfun/flex_fun_execution_context.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 5149148b (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/10699448915).
=> [bot] Merge master/5149148b into rel/dev

gooddata-sdk/gooddata_sdk/catalog/workspace/content_service.py, gooddata-sdk/tests/catalog/fixtures/workspace_content/label_elements.yaml, gooddata-sdk/tests/catalog/test_catalog_workspace_content.py
Add support for paging, pattern filters, sort order and complementary filters to the collect label elements.
One of the test cases had to be removed as the up-to-date test model does not have any suitable attribute anymore.
JIRA: CQ-764
risk: low
=> feat: add support for more label elements parameters

gooddata-flight-server/gooddata_flight_server/__init__.py, gooddata-sdk/tests/sdk/profiles/gooddata.yaml
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 8099bcf7 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/10829040687).
=> [bot] Merge master/8099bcf7 into rel/dev

gooddata-flight-server/gooddata_flight_server/flexfun/flex_fun_execution_context.py, gooddata-flight-server/setup.py, gooddata-flight-server/tests/flexfun/conftest.py, gooddata-flight-server/tests/flexfun/test_flex_fun_execution_context.py
- differentiate between report and label elements executions
- deprecate the generic ExecutionRequest
- get rid of the `attrs` package, it is not worth the hassle
- add some tests
JIRA: CQ-764
risk: low
=> feat: extend FlexFun execution context

.fossa/prepare_and_populate_pipenv.sh
It now has the two FlightRPC-related packages.
JIRA: CQ-785
risk: low
=> chore: update prepare_and_populate_pipenv.sh

.github/workflows/build-release.yaml, .github/workflows/dev-release.yaml, gooddata-flexfun/LICENSE.txt, gooddata-flexfun/gooddata_flexfun/flexfun/flex_fun_execution_context.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to d89a1a47 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/11159033502).
=> [bot] Merge master/d89a1a47 into rel/dev

gooddata-pandas/gooddata_pandas/data_access.py, gooddata-pandas/tests/dataframe/fixtures/filtered_empty_df.yaml, gooddata-pandas/tests/dataframe/test_not_indexed_dataframe.py
Single metric with filter producing empty result failed with index out of bound. This should not happen and an empty dataframe with columns should be returned.
JIRA: PSDK-207
risk: low
=> fix: metric with filter failed

gooddata-pandas/gooddata_pandas/data_access.py, gooddata-pandas/tests/dataframe/fixtures/filtered_empty_df.yaml, gooddata-pandas/tests/dataframe/test_not_indexed_dataframe.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/logical_model/ldm.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 3fdedbd8 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/11236934935).
=> [bot] Merge master/3fdedbd8 into rel/dev

docs/content/en/latest/administration/users/_index.md, docs/content/en/latest/administration/users/create_user_api_token.md, docs/content/en/latest/administration/users/delete_user_api_token.md, docs/content/en/latest/administration/users/get_user_api_token.md, docs/content/en/latest/administration/users/list_user_api_tokens.md, gooddata-sdk/gooddata_sdk/catalog/user/entity_model/api_token.py, gooddata-sdk/gooddata_sdk/catalog/user/service.py, gooddata-sdk/tests/catalog/fixtures/users/test_api_tokens.yaml, gooddata-sdk/tests/catalog/test_catalog_user_service.py
=> feat: add api tokens management

gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/automation.py
=> fix: export definitions in automation

gooddata-sdk/gooddata_sdk/__init__.py
=> feat: add missing user identifier

gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/automation.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 5f63e185 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/11589989987).
=> [bot] Merge master/5f63e185 into rel/dev

gooddata-sdk/gooddata_sdk/compute/service.py
AI APis are still experimental.
We create wrappers for request and result objects later.
=> PoC expose AI use cases

gooddata-sdk/gooddata_sdk/compute/service.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 55d7a7d1 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/11730212045).
=> [bot] Merge master/55d7a7d1 into rel/dev

gooddata-flexconnect/README.md
- simplify
- just guide user to the template
- NOTE: the template repo does not yet exist
JIRA: CQ-894
risk: low
=> doc: cleanup readme

.github/workflows/bump-version.yaml
Checkout as admin to be able to push to protected branch.
JIRA: PSDK-213
risk: low
=> feat: checkout as admin

.github/workflows/bump-version.yaml, gooddata-flexconnect/README.md
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to f79bc213 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/11837844867).
=> [bot] Merge master/f79bc213 into rel/dev

.github/workflows/bump-version.yaml
=> fix: push to rel and master

.github/workflows/bump-version.yaml
=> fix: variables in push step

.github/workflows/bump-version.yaml
=> fix: checkout branch first before push

.github/workflows/bump-version.yaml
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 22d94ae8 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/11839581736).
=> [bot] Merge master/22d94ae8 into rel/dev

gooddata-flexconnect/README.md
=> doc: change git clone to use https schema

gooddata-dbt/setup.py, gooddata-sdk/setup.py
=> chore(requests): bump requests version in setup.py

.github/workflows/build-release.yaml
=> chore: bump slack-github-action

gooddata-sdk/tests/catalog/test_catalog_data_source.py
=> trivial: remove useless self-assignment

.github/workflows/build-release.yaml
Fixes:
* changelog was not part of release body
* failing Slack notification due to missing channel – probably caused by matrix
JIRA: TRIVIAL
risk: low
=> ci: fix issues with changelog and Slack

gooddata-sdk/gooddata_sdk/table.py
When used for internal tabular exports the handling of single-dimensional cases (just metrics or just attributes) seems to cause some breakage when fetching execution data.
The new optional parameter `always_two_dimensional`  will be removed once the tabular export visObj->ExecDef conversions are not done through pysdk (should be pretty soon...).
risk: low
JIRA: CQ-886
=> feat: make single-dim ExecTable handling optional

docs/assets/scss/header.scss, docs/go.mod, docs/go.sum, docs/layouts/partials/navbar.html, gooddata-sdk/gooddata_sdk/table.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to b1e24a70 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/13034334294).
=> [bot] Merge master/b1e24a70 into rel/dev

gooddata-sdk/gooddata_sdk/utils.py, gooddata-sdk/gooddata_sdk/visualization.py, gooddata-sdk/tests/table/fixtures/vis_objs/vis_with_ui_refs.json, gooddata-sdk/tests/table/snapshots/vis_with_ui_refs.snapshot.json
Conversion logic adjusted to follow ui-sdk counterpart. Hence somewhat chaotic usage of defaultType values in some cases.
risk: low
JIRA: CQ-1080
=> fix(sdk): support ui identifier ref conversion

gooddata-pandas/gooddata_pandas/data_access.py, gooddata-sdk/gooddata_sdk/catalog/permission/service.py, gooddata-sdk/gooddata_sdk/catalog/workspace/service.py, pyproject.toml
=> docs: add rule to ruff to check un-documented params

.github/workflows/rw-python-tests.yaml
=> JIRA:GRIF-99

gooddata-sdk/gooddata_sdk/catalog/export/service.py, gooddata-sdk/gooddata_sdk/table.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to c80fd373 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/13382587478).
=> [bot] Merge master/c80fd373 into rel/dev

gooddata-sdk/gooddata_sdk/catalog/data_source/validation/data_source.py
=> docs: add docstrings DataSourceValidator

gooddata-sdk/gooddata_sdk/catalog/data_source/validation/data_source.py, gooddata-sdk/gooddata_sdk/catalog/export/service.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 377dfef8 (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/13398388032).
=> [bot] Merge master/377dfef8 into rel/dev

docs/go.mod, docs/go.sum, gooddata-sdk/gooddata_sdk/catalog/data_source/validation/data_source.py
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 4c45d24d (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/13434260875).
=> [bot] Merge master/4c45d24d into rel/dev

docs/content/en/latest/installation.md
=> docs: Update GD documentation links

gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/compute/model/filter.py
=> feat: add InlineFilter support to PythonSDK

gooddata-sdk/gooddata_sdk/compute/model/base.py, gooddata-sdk/gooddata_sdk/compute/model/filter.py
=> feat: add other params for InlineFilter

gooddata-sdk/gooddata_sdk/compute/compute_to_sdk_converter.py, gooddata-sdk/tests/compute/test_compute_to_sdk_converter.py
There was an incorrect key used for the dimensionality prop.
JIRA: CQ-1267
risk: low
=> fix: fix ranking filter conversion

gooddata-sdk/gooddata_sdk/__init__.py, gooddata-sdk/gooddata_sdk/compute/model/metric.py
=> feat: add support for `InlineMetric`

gooddata-sdk/gooddata_sdk/catalog/workspace/declarative_model/workspace/workspace.py, gooddata-sdk/gooddata_sdk/catalog/workspace/entity_model/workspace.py
=> feat: add description to workspace

docs/content/en/latest/administration/user-groups/_index.md, docs/content/en/latest/administration/user-groups/get_user_group_permissions.md, docs/content/en/latest/administration/user-groups/manage_user_group_permissions.md, docs/content/en/latest/administration/users-and-user-groups/_index.md, docs/content/en/latest/administration/users-and-user-groups/assign_permissions_bulk.md, docs/content/en/latest/administration/users-and-user-groups/revoke_permissions_bulk.md, docs/content/en/latest/administration/users/_index.md, docs/content/en/latest/administration/users/get_user_permissions.md, docs/content/en/latest/administration/users/manage_user_permissions.md, gooddata-sdk/gooddata_sdk/catalog/user/service.py
Add missing documentation to user management methods.
JIRA: TRIVIAL
risk: low
=> docs: user management methods

.github/workflows/build-release.yaml, .github/workflows/dev-release.yaml
:rocket: Automated PR to perform merge from **master** into **rel/dev** with changes up to 1c8cffef (created by https://github.com/gooddata/gooddata-python-sdk/actions/runs/16598269594).
=> [bot] Merge master/1c8cffef into rel/dev

.gitignore, gooddata-pipelines/gooddata_pipelines/api/gooddata_api.py, gooddata-pipelines/gooddata_pipelines/provisioning/entities/users/models/users.py, gooddata-pipelines/gooddata_pipelines/provisioning/entities/users/users.py, gooddata-pipelines/tests/data/profiles.yaml, gooddata-pipelines/tests/data/provisioning/entities/users/existing_upstream_users.json, gooddata-pipelines/tests/data/provisioning/entities/users/profile_response_content.json, gooddata-pipelines/tests/data/provisioning/entities/users/users_input_full_load_modifies_protected_user.json, gooddata-pipelines/tests/data/provisioning/entities/users/users_input_incremental_load_deletes_protected_user.json, gooddata-pipelines/tests/data/provisioning/entities/users/users_input_incremental_load_modifies_protected_user.json, gooddata-pipelines/tests/provisioning/entities/users/test_users.py, gooddata-pipelines/tests/provisioning/test_provisioning.py
=> feat(gooddata-pipelines): prevent modification of current user during user provisioning
